# Generated by Django 4.0.6 on 2022-07-10 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('informacoes_evento', models.TextField()),
                ('data_evento', models.DateField(blank=True)),
                ('imagem_evento', models.ImageField(blank=True, upload_to='./')),
                ('categoria_evento', models.CharField(choices=[('1', 'Período Letivo'), ('2', 'Feriados'), ('3', 'Notícias'), ('4', 'Processo Seletivo'), ('5', 'Benefícios Estudantis'), ('6', 'Cursos Ofertados'), ('7', 'EAD'), ('8', 'Informações de Servidores'), ('9', 'Informações do IFRS')], max_length=1)),
                ('data_atualizacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('visivel', models.BooleanField(default=True)),
            ],
        ),
    ]
