# Generated by Django 4.0.6 on 2022-07-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_categoria_alter_calendario_categoria_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
