# Generated by Django 4.0.6 on 2022-07-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100)),
                ('visivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='calendario',
            name='categoria_evento',
            field=models.IntegerField(choices=[(1, 'Período Letivo'), (2, 'Feriados'), (3, 'Notícias'), (4, 'Processo Seletivo'), (5, 'Benefícios Estudantis'), (6, 'Cursos Ofertados'), (7, 'EAD'), (8, 'Informações de Servidores'), (9, 'Informações do IFRS')]),
        ),
    ]
