# Generated by Django 4.0.6 on 2022-07-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categorias_nome_categoria'),
        ('app', '0014_eventos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
    ]
