# Generated by Django 4.0.6 on 2022-07-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_calendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='numero_de_vagas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
