# Generated by Django 4.0.6 on 2022-07-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_evento_numero_de_vagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nome_do_sistema',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
