# Generated by Django 4.0.6 on 2022-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_evento_nome_do_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ano',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_de_fim',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_de_inicio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='numero_de_vagas',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='semestre',
            field=models.IntegerField(blank=True),
        ),
    ]
