# Generated by Django 4.0.6 on 2022-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_evento_ano_alter_evento_data_de_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_de_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_de_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
