# Generated by Django 4.0.6 on 2022-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_evento_ano_alter_evento_data_de_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='numero_de_vagas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
