# Generated by Django 4.0.6 on 2022-07-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_evento_numero_de_vagas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='arquivo_1',
            field=models.FileField(blank=True, upload_to='arquivo/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='arquivo_2',
            field=models.FileField(blank=True, upload_to='arquivo/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='arquivo_3',
            field=models.FileField(blank=True, upload_to='arquivo/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto_1',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto_2',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto_3',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
