# Generated by Django 4.0.6 on 2022-07-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_evento_numero_de_vagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='sobrenome_do_professor',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
