# Generated by Django 4.0.6 on 2022-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_evento_arquivo_1_alter_evento_arquivo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='arquivo_2',
            field=models.FileField(blank=True, upload_to='./'),
        ),
    ]
