# Generated by Django 4.0.6 on 2022-07-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_evento_arquivo_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='arquivo_2',
            field=models.FileField(blank=True, upload_to='arquivo/%d/%m/%Y/'),
        ),
    ]
