# Generated by Django 4.0.6 on 2022-07-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_evento_arquivo_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_de_fim',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_de_inicio',
            field=models.CharField(blank=True, default='01-01-1999', max_length=10),
            preserve_default=False,
        ),
    ]
