# Generated by Django 4.0.6 on 2022-07-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_evento_sobrenome_do_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='modalidade_de_ingresso',
            field=models.CharField(blank=True, choices=[('ENEM', 'ENEM'), ('Prova', 'Prova'), ('Pessoa Indígena', 'Pessoa Indígena'), ('Processo Seletivo EJA', 'Processo Seletivo EJA'), ('Sorteio', 'Sorteio')], max_length=100),
        ),
    ]
